# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('quantity', models.IntegerField()),
                ('weight', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Baking_Condiments',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Breads_Pasta',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Canned_Goods',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Cleaning_Products',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Dairy',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Frozen_Food',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Meat_Seafood',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Misc',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Paper_Plastic',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Produce',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Snacks',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
        migrations.CreateModel(
            name='Toiletries',
            fields=[
                ('item_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='groceries.Item')),
            ],
            bases=('groceries.item',),
        ),
    ]
