# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-24 20:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groceries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=4),
        ),
    ]
